version: '3.8'
services:
  landing:
    image: cafe1316-frontend
    container_name: cafe1316-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
